apiVersion: v1
kind: Service
metadata:
  name: rhombix-task4-service
spec:
  type: NodePort
  selector:
    app: rhombix-task4
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
      imagePullPolicy: Always